import os, dotenv;
import numpy as np;
import pandas as pd;
from fredapi import Fred;

#
# NOTE BEFORE USE:
# 
# 	I. IF YOU NEED TO VISIT THE FRED PAGE FOR CONTEXT, CREATE URL WITH SERIES ID:
# 		• Generic: https://fred.stlouisfed.org/series/<SERIES ID GOES HERE>
# 		• Example: https://fred.stlouisfed.org/series/BAMLHYH0A0HYM2TRIV
#
# 	II. SOME SERIES ID VALUES MAP TO A 'DISCONTINUED' SERIES
# 		• Can account for why a given series does not provide data up to current date.
# 		• Example: https://fred.stlouisfed.org/series/LTGS (discontinued 1996)
#


#
# Load API keys from .env file
#

dotenv.load_dotenv();
fred_api_key = os.getenv('fred_api_key');


#
# Instantiate FRED object
#

fred = Fred(api_key=fred_api_key);


#
# Define CBOE Volatility Index (VIX) Series IDs
# https://fred.stlouisfed.org/categories/32425
#

series_ids_vix = ['VIXCLS', 'OVXCLS', 'GVZCLS', 'VXVCLS', 'VXNCLS', 'RVXCLS', 'VXOCLS', 'VXTYN', 'VXEEMCLS', 'VXDCLS', 'VXFXICLS', 'VXAZNCLS', 'VXAPLCLS', 'EVZCLS', 'VXEWZCLS', 'VXGOGCLS', 'VXGSCLS', 'VXSLVCLS', 'VXIBMCLS', 'VXGDXCLS', 'VXXLECLS'];



#
# Define Stock Market Index Series IDs
# https://fred.stlouisfed.org/categories/32255
#

series_ids_stock_market = ['SP500', 'DJIA', 'NASDAQCOM', 'WILL5000PR', 'NASDAQ100', 'WILL5000IND', 'WILL5000INDFC', 'DJTA', 'WILLREITIND', 'WILL5000PRFC', 'DJCA', 'WILLLRGCAP', 'WILLSMLCAP', 'WILLRESIPR', 'WILLREITPR', 'DJUA', 'WILLLRGCAPGR', 'WILLLRGCAPVAL', 'WILLMICROCAP', 'WILLSMLCAPPR', 'WILLRESIND', 'WILL4500IND', 'WILLSMLCAPVAL', 'WILLLRGCAPPR', 'WILLSMLCAPGR', 'WILLMIDCAP', 'WILL2500INDVAL', 'WILLSMLCAPVALPR', 'WILLWWW', 'WILL2500IND', 'WILL4500PR', 'WILL2500PR', 'WILLLRGCAPVALPR', 'WILLMICROCAPPR', 'WILLMIDCAPVAL', 'WILLMIDCAPGR', 'WILLLRGCAPGRPR', 'WILLMIDCAPPR', 'WILL2500PRGR', 'WILLMIDCAPGRPR', 'WILL2500PRVAL', 'WILL2500INDGR', 'WILLSMLCAPGRPR', 'WILLMIDCAPVALPR', 'WILLSMLCAP250PR', 'WILLSMLCAP250']



#
# Define Bank of America Bond Market Index Series IDs
# https://fred.stlouisfed.org/categories/32413
#

series_ids_bonds = [
	'BAMLHYH0A0HYM2TRIV', 'BAMLCC0A0CMTRIV', 'BAMLHE00EHYITRIV', 'BAMLHYH0A3CMTRIV', 'BAMLCC4A0710YTRIV',
	'BAMLCC0A4BBBTRIV', 'BAMLCC1A013YTRIV', 'BAMLHYH0A1BBTRIV', 'BAMLEMCBPITRIV', 'BAMLCC0A1AAATRIV',
	'BAMLHYH0A2BTRIV', 'BAMLEMCLLCRPIUSTRIV', 'BAMLCC2A035YTRIV', 'BAMLCC0A2AATRIV', 'BAMLEMHBHYCRPITRIV',
	'BAMLEMRACRPIASIATRIV', 'BAMLCC8A015PYTRIV', 'BAMLCC3A057YTRIV', 'BAMLEMALLCRPIASIAUSTRIV', 'BAMLCC0A3ATRIV',
	'BAMLEMPBPUBSICRPITRIV', 'BAMLEMUBCRPIUSTRIV', 'BAMLCC7A01015YTRIV', 'BAMLEMEBCRPIETRIV', 'BAMLEM1RAAA2ALCRPIUSTRIV',
	'BAMLEMHYHYLCRPIUSTRIV', 'BAMLEM1BRRAAA2ACRPITRIV', 'BAMLEMRLCRPILATRIV', 'BAMLEMXOCOLCRPIUSTRIV', 'BAMLEM2BRRBBBCRPITRIV',
	'BAMLEMNFNFLCRPIUSTRIV', 'BAMLEMIBHGCRPITRIV', 'BAMLEMHGHGLCRPIUSTRIV', 'BAMLEM4RBLLCRPIUSTRIV', 'BAMLEMPUPUBSLCRPIUSTRIV',
	'BAMLEM3BRRBBCRPITRIV', 'BAMLEMRECRPIEMEATRIV', 'BAMLEM5BCOCRPITRIV', 'BAMLEMPTPRVICRPITRIV', 'BAMLEMLLLCRPILAUSTRIV',
	'BAMLEM4BRRBLCRPITRIV', 'BAMLEM3RBBLCRPIUSTRIV', 'BAMLEMELLCRPIEMEAUSTRIV', 'BAMLEMFLFLCRPIUSTRIV', 'BAMLEM2RBBBLCRPIUSTRIV',
	'BAMLEMNSNFCRPITRIV', 'BAMLEMFSFCRPITRIV', 'BAMLEMPVPRIVSLCRPIUSTRIV'
];



#
# Define Treasury Constant Maturity Series IDs
# https://fred.stlouisfed.org/categories/115
#

series_ids_treasury_constant = ['DGS10', 'DFII10', 'DGS2', 'DGS1', 'DGS5', 'DGS30', 'DGS20', 'DGS3MO', 'DGS1MO', 'DFII5', 'DGS3', 'DGS6MO', 'DFII30', 'DGS7'];



#
# Define Corporate Bonds Series IDs
# https://fred.stlouisfed.org/categories/32348
#

series_ids_corporate_bonds = ['BAMLH0A0HYM2', 'BAMLH0A0HYM2EY', 'AAA', 'BAMLC0A4CBBB', 'BAMLC0A0CM', 'DBAA', 'BAMLC0A4CBBBEY', 'BAMLH0A3HYC', 'BAMLH0A3HYCEY', 'BAMLH0A1HYBB', 'BAMLH0A1HYBBEY', 'BAMLHE00EHYIOAS', 'BAMLHE00EHYIEY', 'BAMLH0A2HYBEY', 'BAMLC0A0CMEY', 'BAMLC0A1CAAAEY', 'HQMCB10YR', 'BAMLC0A3CA', 'BAMLH0A2HYB', 'BAMLC0A2CAAEY', 'BAMLC0A3CAEY', 'BAMLC0A1CAAA', 'BAMLC0A2CAA', 'BAMLEMCBPIOAS', 'BAMLC4A0C710YEY', 'HQMCB5YR', 'HQMCB10YRP', 'BAMLEMHBHYCRPIOAS', 'BAMLH0A0HYM2SYTW', 'BAMLEMHBHYCRPIEY', 'BAMLC1A0C13YEY', 'BAMLC8A0C15PYEY', 'HQMCB20YR', 'HQMCB2YRP', 'BAMLC2A0C35YEY', 'HQMCB15YR', 'HQMCB100YR', 'BAMLC3A0C57YEY', 'HQMCB1YR', 'HQMCB30YR', 'BAMLEMCBPIEY', 'HQMCB30YRP', 'HQMCB5YRP', 'BAMLC1A0C13Y', 'HQMCB12YR', 'BAMLEMPBPUBSICRPIEY'];


#
# Define Savings Account Series IDs
# https://fred.stlouisfed.org/categories/33491
#
# Noteworthy/Popular Alternative Investments to Large-Cap, Blue-Chip Equities:
# 	• SNDR: National Deposit Rates: Savings
# 	• MMTY: Treasury Yield: Money Market
# 	• NDR12MCD: National Deposit Rates: 12-Month CD
# 	• TY12MCD: Treasury Yield: 12-Month CD
# 	• TY3MCD: Treasury Yield: 3-Month CD
#

series_ids_savings_accounts = ['SNDR', 'MMTY', 'NDR12MCD', 'MMNDR', 'TY24MCD', 'TY12MCD', 'TY1MCD', 'ICNDR', 'NDR60MCD', 'TY6MCD', 'TY60MCD', 'TY3MCD', 'STY', 'TY36MCD', 'MMNRC', 'SAVNRNJ', 'NDR3MCD', 'NDR6MCD', 'NDR1MCD', 'SNRC', 'MMNDRRCA', 'SNDRRCA', 'NDR24MCD', 'TYRCA24MCD', 'NRC12MCD', 'NRC60MCD', 'NDR36MCD', 'MMTYRCA', 'ICNDRRCA', 'NDR48MCD', 'ICTY', 'TYRCA12MCD', 'NDRRCA36MCD', 'NDRRCA12MCD', 'TYRCA1MCD', 'TYRCA36MCD', 'NRC26MCD', 'ICNRC', 'STYRCA', 'ICTYRCA', 'NRC3MCD', 'SAVRCNJ', 'NDRRCACD', 'TYRCA60MCD', 'NDRRCA60MCD', 'TYRCA3MCD', 'NRC1MCD', 'NDRRCA6MCD', 'TYRCA6MCD', 'NRC24MCD'];